# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MedSync4.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MedSync4.0
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'
pod 'SDWebImage'


  target 'MedSync4.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MedSync4.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
